"""Thin async HTTP client for the Open Green Button proxy server.

Only covers the endpoints needed by the config flow in Phase 3.0/3.1:
  - GET /utilities       — discovery for the utility picker
  - POST /claim/{code}   — single-use claim-code redemption

`/proxy/usage` and `/proxy/refresh` are added when the coordinator lands (Phase 3.3).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any

import aiohttp

from .const import API_VERSION

_LOGGER = logging.getLogger(__name__)


@dataclass(frozen=True, slots=True)
class UtilitySummary:
    """A utility entry as returned by GET /utilities."""

    id: str
    display_name: str


@dataclass(frozen=True, slots=True)
class ClaimResponse:
    """A successful POST /claim/{code} response."""

    utility_id: str
    encrypted_refresh_blob: str
    proxy_token: str
    subscription_uri: str | None
    scope: str | None
    current_api_version: str


class OpenGbApiError(Exception):
    """Catch-all proxy-server error."""


class OpenGbClaimNotFoundError(OpenGbApiError):
    """The claim code was unknown, already used, or expired (HTTP 410)."""


class OpenGbApi:
    """Async client for the Open Green Button proxy server."""

    def __init__(self, session: aiohttp.ClientSession, server_base_url: str) -> None:
        """Hold an aiohttp session (typically HA's shared one) and the proxy base URL."""
        self._session = session
        self._base = server_base_url.rstrip("/")

    @property
    def headers(self) -> dict[str, str]:
        """Common request headers. Stripe-style API version on every call."""
        return {"OpenGB-Api-Version": API_VERSION}

    async def list_utilities(self) -> list[UtilitySummary]:
        """Fetch the configured utility list. Returns [] if the server has none configured."""
        url = f"{self._base}/utilities"
        async with self._session.get(url, headers=self.headers) as resp:
            if resp.status != 200:
                body = await resp.text()
                raise OpenGbApiError(f"GET /utilities returned {resp.status}: {body[:200]}")
            payload: list[dict[str, Any]] = await resp.json()
        return [UtilitySummary(id=item["id"], display_name=item["displayName"]) for item in payload]

    async def redeem_claim(self, claim_code: str) -> ClaimResponse:
        """Atomically redeem a one-time claim code generated by the OAuth callback.

        Raises:
            OpenGbClaimNotFoundError: claim code unknown / expired / already used (HTTP 410).
            OpenGbApiError: any other failure (network, 4xx other than 410, 5xx).
        """
        url = f"{self._base}/claim/{claim_code}"
        async with self._session.post(url, headers=self.headers) as resp:
            if resp.status == 410:
                raise OpenGbClaimNotFoundError("Claim code is unknown, expired, or already used")
            if resp.status != 200:
                body = await resp.text()
                raise OpenGbApiError(f"POST /claim returned {resp.status}: {body[:200]}")
            payload: dict[str, Any] = await resp.json()
        return ClaimResponse(
            utility_id=payload["utilityId"],
            encrypted_refresh_blob=payload["encryptedRefreshBlob"],
            proxy_token=payload["proxyToken"],
            subscription_uri=payload.get("subscriptionUri"),
            scope=payload.get("scope"),
            current_api_version=payload["currentApiVersion"],
        )
